py36:
  image: python:3.6
  script:
  - pip install tox
  - tox -e py36

py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e format,mypy,py37,pep8,setuppy,manifest

pages:
  image: python:3.7
  script:
  - pip install sphinx solar_theme
  - python setup.py install
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/source/ hypercorn/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

h2spec:
  image: python:3.7
  script:
  - python setup.py install
  - cd compliance/h2spec && nohup hypercorn --keyfile key.pem --certfile cert.pem server:App &
  - wget https://github.com/summerwind/h2spec/releases/download/v2.2.0/h2spec_linux_amd64.tar.gz
  - tar -xvf h2spec_linux_amd64.tar.gz
  - sleep 10
  - ./h2spec -tk -h 127.0.0.1 -p 5000

h2spec-trio:
  image: python:3.7
  script:
  - python3 -m pip install trio .
  - cd compliance/h2spec && nohup hypercorn --keyfile key.pem --certfile cert.pem -k trio server:App &
  - wget https://github.com/summerwind/h2spec/releases/download/v2.2.0/h2spec_linux_amd64.tar.gz
  - tar -xvf h2spec_linux_amd64.tar.gz
  - sleep 10
  - ./h2spec -tk -h 127.0.0.1 -p 5000 -o 10

autobahn:
  image: python:2.7.14-alpine3.6
  script:
  - apk --update add build-base libressl libressl-dev ca-certificates libffi-dev python3
  - pip install cryptography==2.3.1 autobahntestsuite
  - python3 setup.py install
  - cd compliance/autobahn && nohup hypercorn server:App &
  - while ! netstat -l -t | grep -q 5000; do sleep 1; done
  - cd compliance/autobahn && wstest -m fuzzingclient && python summarise.py
  artifacts:
    paths:
    - compliance/autobahn/reports/servers/

autobahn-trio:
  image: python:2.7.14-alpine3.6
  script:
  - apk --update add build-base libressl libressl-dev ca-certificates libffi-dev python3 python3-dev
  - pip install cryptography==2.3.1 autobahntestsuite
  - python3 -m pip install trio .
  - cd compliance/autobahn && nohup hypercorn -k trio server:App &
  - while ! netstat -l -t | grep -q 5000; do sleep 1; done
  - cd compliance/autobahn && wstest -m fuzzingclient && python summarise.py
  artifacts:
    paths:
    - compliance/autobahn/reports/servers/
